"""
bhaskera-infer — command-line interface for Bhaskera inference.

Examples
--------
    # Basic generation
    bhaskera-infer --config config.yaml --prompt "Once upon a time"

    # TurboQuant KV cache
    bhaskera-infer --config config.yaml \\
        --prompt "Explain attention mechanisms" \\
        --kv-cache turboquant --key-bits 4 --value-bits 2

    # Speculative decoding
    bhaskera-infer --config config.yaml \\
        --prompt "The answer is" \\
        --speculative --draft-model Qwen/Qwen2.5-0.5B-Instruct

    # From file, multiple prompts
    bhaskera-infer --config config.yaml --prompt-file prompts.txt

    # No config file needed — use defaults
    bhaskera-infer --model tiiuae/falcon-7b --prompt "Hello!"
"""
from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path
from typing import List

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s — %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger("bhaskera.infer")


# ---------------------------------------------------------------------------
# Argument parser
# ---------------------------------------------------------------------------

def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="bhaskera-infer",
        description="Bhaskera LLM inference engine CLI",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    # Config / model
    p.add_argument("--config",  default=None,   help="Path to Bhaskera YAML config")
    p.add_argument("--model",   default=None,   help="HuggingFace model id (overrides config)")
    p.add_argument("--device",  default="auto", help="Device: auto | cuda | cpu | mps")

    # Input
    inp = p.add_mutually_exclusive_group(required=True)
    inp.add_argument("--prompt",      default=None, help="Single prompt string")
    inp.add_argument("--prompt-file", default=None, metavar="FILE",
                     help="File with one prompt per line")

    # Generation
    p.add_argument("--max-new-tokens", type=int,   default=None)
    p.add_argument("--temperature",    type=float, default=None)
    p.add_argument("--top-p",          type=float, default=None)
    p.add_argument("--top-k",          type=int,   default=None)
    p.add_argument("--no-sample",      action="store_true",
                   help="Greedy decoding (overrides do_sample=true in config)")

    # KV cache
    p.add_argument("--kv-cache", default=None, choices=["static", "turboquant", "none"],
                   help="KV cache strategy")
    p.add_argument("--key-bits",          type=int, default=None,
                   help="TurboQuant: bits for keys (default 4)")
    p.add_argument("--value-bits",        type=int, default=None,
                   help="TurboQuant: bits for values (default 2)")
    p.add_argument("--residual-window",   type=int, default=None,
                   help="TurboQuant: fp16 residual window size (default 128)")

    # Speculative decoding
    p.add_argument("--speculative",    action="store_true",
                   help="Enable speculative decoding")
    p.add_argument("--draft-model",    default=None,
                   help="Draft model HuggingFace id for speculative decoding")
    p.add_argument("--num-draft-tokens", type=int, default=None,
                   help="Tokens generated by draft per step (default 5)")

    # Misc
    p.add_argument("--torch-compile",  action="store_true",
                   help="Apply torch.compile for faster decode")
    p.add_argument("--return-full",    action="store_true",
                   help="Include the prompt in the output")
    p.add_argument("--verbose", "-v",  action="store_true",
                   help="Enable DEBUG logging")

    return p


# ---------------------------------------------------------------------------
# Config assembly
# ---------------------------------------------------------------------------

def _build_config(args: argparse.Namespace):
    """Build a Bhaskera Config, applying CLI overrides on top."""
    from bhaskera.config import (
        Config,
        InferenceConfig,
        TurboQuantConfig,
        SpeculativeConfig,
    )

    if args.config:
        from bhaskera.config import load_config
        cfg = load_config(args.config)
    else:
        cfg = Config()

    # Model override
    if args.model:
        cfg.model.name = args.model

    if args.device:
        cfg.inference.device = args.device

    # Generation overrides
    infer = cfg.inference
    if args.max_new_tokens is not None:
        infer.max_new_tokens = args.max_new_tokens
    if args.temperature is not None:
        infer.temperature = args.temperature
    if args.top_p is not None:
        infer.top_p = args.top_p
    if args.top_k is not None:
        infer.top_k = args.top_k
    if args.no_sample:
        infer.do_sample = False
    if args.torch_compile:
        infer.torch_compile = True

    # KV cache overrides
    if args.kv_cache:
        infer.kv_cache = args.kv_cache
    if infer.kv_cache == "turboquant":
        if args.key_bits is not None:
            infer.turboquant.key_bits = args.key_bits
        if args.value_bits is not None:
            infer.turboquant.value_bits = args.value_bits
        if args.residual_window is not None:
            infer.turboquant.residual_window = args.residual_window
        infer.turboquant.enabled = True

    # Speculative decoding overrides
    if args.speculative:
        infer.speculative.enabled = True
    if args.draft_model:
        infer.speculative.draft_model_name = args.draft_model
        infer.speculative.enabled = True
    if args.num_draft_tokens is not None:
        infer.speculative.num_draft_tokens = args.num_draft_tokens

    return cfg


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main(argv: List[str] = None) -> None:
    parser = _build_parser()
    args   = parser.parse_args(argv)

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    # ── Prompts ──────────────────────────────────────────────────────
    if args.prompt:
        prompts = [args.prompt]
    else:
        path = Path(args.prompt_file)
        if not path.exists():
            parser.error(f"Prompt file not found: {args.prompt_file}")
        with open(path) as f:
            prompts = [line.rstrip("\n") for line in f if line.strip()]
        if not prompts:
            parser.error(f"No prompts found in {args.prompt_file}")
        logger.info(f"Loaded {len(prompts)} prompts from {args.prompt_file}")

    # ── Config ───────────────────────────────────────────────────────
    cfg = _build_config(args)

    # ── Engine ───────────────────────────────────────────────────────
    from bhaskera.inference import InferenceEngine

    engine = InferenceEngine(cfg)
    engine.load()

    # ── Log active settings ───────────────────────────────────────────
    infer = cfg.inference
    logger.info(
        f"Settings: kv_cache={infer.kv_cache!r} "
        f"temperature={infer.temperature} top_p={infer.top_p} "
        f"max_new_tokens={infer.max_new_tokens} "
        f"speculative={infer.speculative.enabled}"
    )

    if infer.kv_cache == "turboquant":
        logger.info(
            f"TurboQuant: K{infer.turboquant.key_bits}/V{infer.turboquant.value_bits} bits, "
            f"residual_window={infer.turboquant.residual_window}, "
            f"protected_layers={infer.turboquant.protected_layers}"
        )

    # ── Generate ─────────────────────────────────────────────────────
    import time
    t0 = time.time()
    outputs = engine.generate(
        prompts,
        return_full_text=args.return_full,
    )
    elapsed = time.time() - t0

    # ── Print results ──────────────────────────────────────────────────
    separator = "─" * 72
    for i, (prompt, output) in enumerate(zip(prompts, outputs)):
        if len(prompts) > 1:
            print(f"\n{separator}")
            print(f"[{i + 1}/{len(prompts)}] Prompt: {prompt[:80]}{'…' if len(prompt) > 80 else ''}")
            print(separator)
        print(output)

    print(f"\n{separator}")
    print(f"Generated {len(prompts)} response(s) in {elapsed:.2f}s")

    # KV cache stats (TurboQuant)
    stats = engine.kv_cache_stats()
    if stats and "compression_ratio" in stats:
        print(
            f"TurboQuant KV cache: {stats['tq_mb']:.1f} MB "
            f"(bf16 baseline: {stats['bf16_mb']:.1f} MB, "
            f"ratio: {stats['compression_ratio']:.1f}×)"
        )


if __name__ == "__main__":
    main()
